import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header"; // Import Header component

// Initialize the Inter font
const inter = Inter({ subsets: ["latin"] });

// Set metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Include Header component */}
        <Header />
        {/* Render the children (content of each page) */}
        {children}
      </body>
    </html>
  );
}
